[package]
authors = ["Erik Johnston"]
edition = "2018"
name = "github-matrix-project"
version = "0.1.0"

[dependencies]
actix = "0.7.9"
actix-web = "0.7.18"
futures = "0.1.25"
reqwest = "0.9.11"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
tokio = "0.1.16"
