[package]
authors = ["Erik Johnston"]
edition = "2018"
name = "github-matrix-project"
version = "0.2.1"

[dependencies]
serde = "1.0.124"
serde_derive = "1.0.124"
serde_json = "1.0.64"
tokio = { version = "1.3.0", features = ["full"] }
reqwest = { version = "0.11.5", features = ["json"] }
anyhow = "1.0.38"
