[package]
authors = ["Erik Johnston"]
edition = "2018"
name = "github-matrix-project"
version = "0.1.1"

[dependencies]
serde = "1.0.124"
serde_derive = "1.0.124"
serde_json = "1.0.64"

hyper = { version = "0.14.4", features = ["server"] }
tokio = { version = "1.3.0", features = ["full"] }
reqwest = { version = "0.11.2", features = ["json"] }
anyhow = "1.0.38"
